# Generated by Django 4.0.1 on 2023-10-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boo_mem',
            fields=[
                ('book_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('book_qty', models.IntegerField()),
                ('book_price', models.IntegerField()),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
    ]
