# Generated by Django 4.0.1 on 2023-10-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('book_mem', models.CharField(max_length=30)),
                ('book_qty', models.IntegerField()),
                ('book_price', models.IntegerField()),
                ('book_schedule', models.IntegerField()),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marina',
            fields=[
                ('mar_nm', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('mar_add1', models.CharField(max_length=100)),
                ('mar_add2', models.CharField(max_length=80)),
                ('mar_lat', models.FloatField()),
                ('mar_lon', models.FloatField()),
            ],
            options={
                'db_table': 'marina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mem_pass', models.CharField(max_length=20)),
                ('mem_name', models.CharField(max_length=15)),
                ('mem_regno1', models.IntegerField()),
                ('mem_mail', models.CharField(max_length=30)),
                ('mem_add1', models.CharField(max_length=100)),
                ('mem_add2', models.CharField(max_length=80)),
                ('mem_hp', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sch_no', models.IntegerField(primary_key=True, serialize=False)),
                ('sch_marina', models.CharField(max_length=30)),
                ('sch_arrival', models.CharField(max_length=30)),
                ('sch_taxi', models.CharField(max_length=10)),
                ('sch_stime', models.CharField(max_length=30)),
                ('sch_etime', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_mar', models.CharField(max_length=30)),
                ('ser_gu', models.CharField(max_length=10)),
                ('ser_group', models.CharField(max_length=50)),
                ('ser_nm', models.CharField(max_length=50)),
                ('ser_add', models.CharField(max_length=100)),
                ('ser_tel', models.CharField(max_length=20)),
                ('ser_img', models.CharField(max_length=300)),
                ('ser_distance', models.FloatField()),
                ('ser_url', models.CharField(max_length=100)),
                ('ser_lat', models.FloatField()),
                ('ser_lon', models.FloatField()),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tra_mar', models.CharField(max_length=30)),
                ('tra_num', models.IntegerField()),
                ('tra_nm', models.CharField(max_length=50)),
                ('tra_time', models.CharField(max_length=50)),
                ('tra_bus', models.CharField(max_length=20)),
                ('tra_way', models.CharField(max_length=100)),
                ('tra_route', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'traffic',
                'managed': False,
            },
        ),
    ]
