# Generated by Django 4.0.1 on 2023-10-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('book_no', models.IntegerField(primary_key=True, serialize=False)),
                ('book_mem', models.CharField(max_length=30)),
                ('book_qty', models.IntegerField()),
                ('book_price', models.CharField(max_length=15)),
                ('book_marina', models.CharField(max_length=30)),
                ('book_arrival', models.CharField(max_length=30)),
                ('book_taxi', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marina',
            fields=[
                ('mar_nm', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('mar_add1', models.CharField(max_length=100)),
                ('mar_add2', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'marina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mem_pass', models.CharField(max_length=20)),
                ('mem_name', models.CharField(max_length=15)),
                ('mem_regno1', models.IntegerField()),
                ('mem_regno2', models.IntegerField()),
                ('mem_zip', models.IntegerField()),
                ('mem_add1', models.CharField(max_length=100)),
                ('mem_add2', models.CharField(max_length=80)),
                ('mem_hp', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sch_no', models.IntegerField(primary_key=True, serialize=False)),
                ('sch_marina', models.CharField(max_length=30)),
                ('sch_arrival', models.CharField(max_length=30)),
                ('sch_taxi', models.CharField(max_length=10)),
                ('sch_stime', models.CharField(max_length=30)),
                ('sch_etime', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
    ]
