# Generated by Django 4.0.1 on 2023-10-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ser_mar', models.CharField(max_length=30)),
                ('ser_gu', models.CharField(max_length=10)),
                ('ser_group', models.CharField(max_length=50)),
                ('ser_nm', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ser_add', models.CharField(max_length=100)),
                ('ser_tel', models.CharField(max_length=20)),
                ('ser_img', models.CharField(max_length=300)),
                ('ser_distance', models.IntegerField()),
                ('ser_url', models.CharField(max_length=100)),
                ('ser_lat', models.FloatField()),
                ('ser_lon', models.FloatField()),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tra_mar', models.CharField(max_length=30)),
                ('tra_num', models.IntegerField()),
                ('tra_nm', models.CharField(max_length=50)),
                ('tra_time', models.CharField(max_length=50)),
                ('tra_bus', models.CharField(max_length=20)),
                ('tra_way', models.CharField(max_length=100)),
                ('tra_route', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'traffic',
                'managed': False,
            },
        ),
    ]
